- name: Filters
  hosts: localhost
  vars:
    URL: https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
  tasks:
    - name: filter
      debug:
        msg: "{{ URL |  split('/') | last | regex_replace('.tar.gz', '')}}"
